### PR TITLE
Sending an email and reply back to another email issue solved

### PR DESCRIPTION
**Pull request by VijalPatel**

### CODE REVIEW

**Comment by mathe42** [comment]
Just use the option `replyTo`. The option `inReplyTo;` accepts a mail ID so it can refrence a different email.

**Comment by VijalPatel** [comment]
When I use replyTo then it now worked, it will reply to authenticate email.
we have to use exert word Reply-To.

**Comment by mathe42** [comment]
It is a bug in line 136 not 127 will fix that

**Comment by mathe42** [comment]
fixed in ac07d84a230a06ddd67fdb52f7605e92487330a9

**Comment by VijalPatel** [comment]
Thank you so much.
Can you please update in https://deno.land/?
When I call Deno land package its loading old one file.

**Comment by mathe42** [comment]
Import from https://raw.githubusercontent.com/EC-Nordbund/denomailer/ac07d84a230a06ddd67fdb52f7605e92487330a9/mod.ts for now. I will create a new release when #63 is merged.

**Pull request closed without merging**
